### ISSUE TITLE
Bizarre defaults. (old title: Program does not work...at all.)

### ISSUE THREAD

**Issue by bradenbest** [jonathankoren/imlibsetroot#2]
I have tried it with multiple options and filetypes and it doesn't do anything. Neither do any of the perl scripts.

While `feh --bg-fill image.png` will correctly fill my root window's background with an image, `./imlibsetroot -s image.png` will do absolutely nothing.

Well, actually, that's a lie. When I try to run it, it sets the background to a black void. It's not nothing, but it might as well be.

Environment:
**Arch**: x86_64
**Dist**: Ubuntu
**Disp. Server**: X11
**WM**: DWM 6.1
**Desktop**: (none)

**Edit**: I finally got it to work, but only after reading a user's example on a forum. Please include `-x e -s` as a "basic usage example" in `README.md`, because there's no way I would have guessed that (I often forget that Xinerama is a thing, because most programs that use it tend to do the same for all monitors by default). When it didn't work the way I expected with just `-s`, I assumed it was broken. Also, I think `-x e` should be the default behaviour, as it would do the same thing whether the user has 1, 2, or 50 monitors. The way I see it, there's no logical reason for the current default behaviour.

**Comment by bradenbest** [comment]
I found on a forum that it does work with `imlibsetroot -x e -s <image>`. Verified.

Why? Why doesn't just `-s` work? Why isn't `-x e -s` the default behavior? Why isn't `-x e -s` listed as a "basic usage" example in the readme?

I'm going to change the title of this issue. The "not working issue isn't the issue now.

**Comment by jonathankoren** [comment]
If you're getting a black background, you're using it wrong.

Why isn't -e the default behavior? Because **the whole point** of this was to have background spanning. Treating each monitor as a separate entity while having the desktop and windows be able to span monitors is bizarre and broken, and has been for 20 years.
