### ISSUE TITLE
requires changing x to X to build on archlinux

### ISSUE THREAD

**Issue by ohnonot** [jonathankoren/imlibsetroot#5]
i know next to nothing about compiling, but after getting this error:

```
$ make
(...)
/usr/bin/ld: cannot find -lxinerama
/usr/bin/ld: cannot find -lx11
```

i changed all occurences of `xinerama` and `x11` to `Xinerama` and `X11`, and lo and behold, it worked!

i'm not sure if this can be fixed while keeping it cross-platform, but i thought it worth mentioning.

**Comment by jonathankoren** [comment]
fixed
